### ISSUE TITLE
Update to match the current CloudFormation infrastructure code

### ISSUE THREAD

**Issue by cristim** [LeanerCloud/terraform-aws-autospotting#11]
The CloudFormation code implements a few additional features that haven't yet been ported to Terraform:

- regional Lambda functions that handle the spot termination notification
- execution schedule
- Install everything using a StackSet (questionable)

**Comment by bfin** [comment]
The module can handle cron schedules as is via the `lambda_run_frequency` variable, which can be set to something like `cron(0 20 * * ? *)` or `rate(5 minutes)`, though I suppose the variable name is misleading.

**Comment by cristim** [comment]
Thanks, but there's a bit of difference.

The Lambda function schedule is a global parameter that will stop AutoSpotting from running for all the groups, it's also leaving unattached spot instances in limbo until the next run.

This feature assumed that the Lambda function is running as usual but behaves differently when inside/outside the configured schedule. It's also configurable on a per group basis using the usual tagging mechanism, so you can have groups handled differently, and it will clean up the unattached spot instances when running outside the configured schedule for  the current group.

The main use case is for development environments where spot replacement may not be desirable during the office hours in order not to impact the developers or running of tests against the dev groups. In the same account you may have groups where this is not a problem or where you maybe only want to replace instances during the day so engineers are available in case something is not working as expected.
