### ISSUE TITLE
Lambda error on 0.1.2 fork/exec /var/task/AutoSpotting: no such file or directory: PathError null

### ISSUE THREAD

**Issue by tyler-ground** [LeanerCloud/terraform-aws-autospotting#17]
Deployed the 0.1.2 module and CloudWatch is throwing an error when it triggers

fork/exec /var/task/AutoSpotting: no such file or directory: PathError null

**Comment by bfin** [comment]
Did you deploy from the Terraform Registry or the Github repository? (See [sources](https://github.com/AutoSpotting/terraform-aws-autospotting#sources))

**Comment by tyler-ground** [comment]
I deployed with:

module "autospotting" {
  source         = "AutoSpotting/autospotting/aws"
  version        = "0.1.2"
}


Note: I fixed this by manually uploading the latest nightly

**Comment by tyler-ground** [comment]
Hence, we can close this on my account but I think it's worth leaving here in a Closed state if someone else encounters the same problem :)

**Comment by tyler-ground** [comment]
Going to close and someone can reopen if they also encounter the problem.

**Comment by cristim** [comment]
@tyler-ground if you have some time please create a PR that makes the default configuration to use the official binaries, so that other people don't run into this issue.
