### ISSUE TITLE
Update Terraform Registry and bump version

### ISSUE THREAD

**Issue by bfin** [LeanerCloud/terraform-aws-autospotting#2]
Just a few more things to finalize the move from the upstream repo:
- remove the old repo (cristim/terraform-aws-autospotting) from the Terraform Registry
- [publish](https://registry.terraform.io/github/create) the renamed repo to the Terraform Registry
- bump the version (probably to 0.1.0) here

**Comment by bfin** [comment]
Actually, another option would be to just drop the module from the Terraform Registry altogether. The module can still be used from this repo, users would just have to supply the binary. Depends on whether you want to tag releases here (necessary for the Terraform Registry to pick up versions) or just merge PRs and be done with it.

**Comment by cristim** [comment]
I deleted the module created when the repo was available as my personal github username, but it turns out I can't create it using the AutoSpotting organization. Any suggestions?

**Comment by cristim** [comment]
I figured it out, I needed to revoke the permissions to my Github account and grant the TF registry access once again, including access to the AutoSpotting organization.

The module now appears in the Terraform registry at https://registry.terraform.io/modules/AutoSpotting/autospotting/aws/

**Comment by bfin** [comment]
Good to know! I just ran into the same issue when testing with a fork from my org. Thanks for documenting the fix.
