### ISSUE TITLE
v0.1.3 fails with incorrect function name

### ISSUE THREAD

**Issue by vikas027** [LeanerCloud/terraform-aws-autospotting#24]
I am facing below issue with `v0.1.3`, however, `v0.1.2` works absolutely fine. I am using terraform v0.12.24 just in case if it matters.

```bash
Error: "function_name" doesn't comply with restrictions ("^(arn:[\\w-]+:lambda:)?([a-z]{2}-(?:[a-z]+-){1,2}\\d{1}:)?(\\d{12}:)?(function:)?([a-zA-Z0-9-_]+)(:(\\$LATEST|[a-zA-Z0-9-_]+))?$"): ""

  on .terraform/modules/autospotting/main.tf line 54, in resource "aws_lambda_permission" "cloudwatch_events_permission":
  54: resource "aws_lambda_permission" "cloudwatch_events_permission" {v
```

**Comment by lukvdborne** [comment]
Getting the same error. If we use master, we're getting this:

```
Error: Unsupported attribute

  on .terraform/modules/autospotting/modules/lambda/outputs.tf line 2, in output "function_name":
   2:   value = aws_lambda_function.autospotting.function_name
    |----------------
    | aws_lambda_function.autospotting is empty tuple

This value does not have any attributes.


Error: Unsupported attribute

  on .terraform/modules/autospotting/modules/lambda/outputs.tf line 6, in output "arn":
   6:   value = aws_lambda_function.autospotting.arn
    |----------------
    | aws_lambda_function.autospotting is empty tuple

This value does not have any attributes.
```
Not sure if it's related, but it also has to do with the function name.

**Comment by lukvdborne** [comment]
We have 2 virtually identical environment (staging vs acceptance & production) with the same terraform version, aws provider version, autospotting module configuration and lambda, where this is not a problem.. This is very strange. Could this be state related?

**Comment by cristim** [comment]
@lukvdborne Please compare the state contents and also the output of a describe call of this Lambda function between those two environments.

**Comment by lukvdborne** [comment]
The state of the resource in question is the same, whether it has been terraformed with 0.1.2 or with master:

```
# module.autospotting.aws_lambda_permission.cloudwatch_events_permission:
resource "aws_lambda_permission" "cloudwatch_events_permission" {
    action        = "lambda:InvokeFunction"
    function_name = "autospotting"
    id            = "AllowExecutionFromCloudWatch"
    principal     = "events.amazonaws.com"
    source_arn    = "arn:aws:events:eu-west-1:123456789012:rule/autospotting_frequency"
    statement_id  = "AllowExecutionFromCloudWatch"
}
```


Regarding my error on master, the environment where master works has a resource called `module.autospotting.module.aws_lambda_function.aws_lambda_function.autospotting`, whilst the environment where it throws the empty tuple error, it's `module.autospotting.module.aws_lambda_function.aws_lambda_function.autospotting[0]`

Sounds like it makes sense that 0.1.3 throws that error, since if the result is really a list, it should output `function_name = module.aws_lambda_function[0].function_name` on line 54 (which in itself doesn't make sense as there's only 1 lambda).

**Comment by cristim** [comment]
I think this is the culprit:

https://github.com/AutoSpotting/terraform-aws-autospotting/commit/c0d56202794ad61b750b02ea5cbb1816ddd2a1f1#diff-b55f6185b4d15f69059c6d3fac788c60L7

Previously we had a count conditional in order to choose from two different implementations of the Lambda function. We recently simplified the code to have a single implementation and we deleted the count condition.

The count made it return a list where we always had to access the first item for the output value.

Without it we now need to fix the output.


Later edit: the same commit changed the output to work with the current implementation, so I have no idea why you are getting this error.

Have you tried to destroy and recreate with the current code?

**Comment by vikas027** [comment]
> Have you tried to destroy and recreate with the current code?

I have tried the same. I am facing the same error even on a fresh installation

**Comment by cristim** [comment]
Okay, I'll have a look at this within the next few days

**Comment by bfin** [comment]
@vikas027 I think this is related to the problem that was addressed in PR #21. Try with anything from commit c0d5620 on.

```hcl
module "autospotting" {
  source = "github.com/autospotting/terraform-aws-autospotting?ref=c0d5620" # or ref=master
}
```

@cristim Bumping the version should fix this

**Comment by cristim** [comment]
Yeah, I just realized that I forgot to cut a new release after that change, sorry about that.

I'll create one shortly.

**Comment by cristim** [comment]
I just tagged 0.1.4, please give that a try and let me know if you still notice any issues.

**Comment by vikas027** [comment]
Thanks @cristim, I am able to deploy `0.1.4` successfully but now I have another issue.

I have a tag named `spot_enabled=true` in the `autospotting` module as well as my autoscaling groups, with `0.1.4` but seems like `autospotting` is unable to pick that as I have this in my lambda logs `2020/05/04 23:31:27 region.go:107: ap-southeast-2 has no enabled AutoScaling groups` 

```
module autospotting {
  source                                    = "github.com/autospotting/terraform-aws-autospotting?ref=0.1.4"
  autospotting_regions_enabled              = "ap-southeast-2*"
  autospotting_tag_filters                  = "spot_enabled=true"
  autospotting_allowed_instance_types       = "m4.large,m4.xlarge"
<redacted>
}
```

This works absolutely fine with `0.1.2`. Has something changed lately?

**Comment by bfin** [comment]
The default autospotting binary changed between v0.1.2 and v0.1.3. If you think it’s a terraform issue, try specifying the same binary with v0.1.2 and v0.1.4

**Comment by vikas027** [comment]
> The default autospotting binary changed between v0.1.2 and v0.1.3. If you think it’s a terraform issue, try specifying the same binary with v0.1.2 and v0.1.4

I have used the same binary with these versions and the exact code (in the previous comment).

**Comment by vikas027** [comment]
Everything is working as expected now, not sure why the `v0.1.4` gave me that weird issue but now is working fine. I will create a new issue if something crops up again.

Kudos to you guys to identify and fix the problem so quickly.

**Comment by cristim** [comment]
thanks for the confirmation, great to hear that it works!

**Comment by lukvdborne** [comment]
@cristim I still had problems with our staging environment. Even with 0.1.4 I kept getting https://github.com/AutoSpotting/terraform-aws-autospotting/issues/24#issuecomment-622984010. With 0.1.2 this worked fine, with 0.1.3 I got the same error as OP did. With master/0.1.4 I got "my" error.

What I did to solve was pin the module 0.1.2, then execute:

`terraform state rm module.autospotting.module.label.data.null_data_source.tags_as_list_of_maps\[0\]`
`module.autospotting.module.aws_lambda_function.module.label.data.null_data_source.tags_as_list_of_maps\[0\]`

then (not sure if this was necessary, but it shouldn't hurt either) comment out the entire module definition, run `terraform apply` which should now be able to destroy the autospotting resources.

Then I could uncomment the module definition and set it to 0.1.4. After a new init, an apply works fine now.

**Comment by bfin** [comment]
This is good input. We should probably start including an upgrade guide when appropriate and either stick to or abandon the semantic versioning, which has been misleading with the patch-level version bumps. I'm definitely guilty of not identifying breaking changes in my PRs – I'll be more careful in the future.

**Comment by vikas027** [comment]
> What I did to solve was pin the module 0.1.2, then execute:
> 
> `terraform state rm module.autospotting.module.label.data.null_data_source.tags_as_list_of_maps\[0\]`
> `module.autospotting.module.aws_lambda_function.module.label.data.null_data_source.tags_as_list_of_maps\[0\]`

I didn't have to do this as I was deploying to a fresh AWS account

**Comment by cristim** [comment]
I wouldn't commit to ensure that upgrades work between versions. 

I would rather document an upgrade procedure based on immutable infrastructure principles: `terraform destroy`, bump version and then `terraform apply` with the new code.

We have no state to lose and the configuration wouldn't be changed if you destroy the infrastructure.

**Comment by vikas027** [comment]
> I would rather document an upgrade procedure based on immutable infrastructure principles: `terraform destroy`, bump version and then `terraform apply` with the new code.

Yep, something like this should do the job well
```bash
$ terraform destroy -target=module.autospotting -force
```

**Comment by cristim** [comment]
Thanks @vikas027.

In most cases the regular updates should work but we can offer this as a recovery mechanism in case of failed upgrades.
