### ISSUE TITLE
Feature Request - Clean up Orphan Spot Instances

### ISSUE THREAD

**Issue by vikas027** [LeanerCloud/terraform-aws-autospotting#25]
### Problem
I have a workflow where any change in the userdata creates a new launch configuration and an autoscaling group and the old launch configuration and autoscaling group is deleted. Now, in the condition where Autospotting has launched a VM but it has not been added to the autoscaling group if in the meantime a change has been triggered the spot instance (with the old launch configuration) remains active.

Please see below example
- Terraform creates a `launch-config-A` and `autoscaling-group-A`
- Autospotting launches a new instance (using `launch-config-A`), say `spot-instance-A`, but it is not added to the `autoscaling-group-A`
- There is a change in userdata which creates `launch-config-B` and `autoscaling-group-B` and deletes `launch-config-A` and `autoscaling-group-A`

Now, in this case, `spot-instance-A` is in an orphan state since it's `launch-config-A` and `autoscaling-group-A` are already deleted.

### Probable Solution
Maybe we can check below tags of the spot instance and if the autoscaling group is not present, then terminate the spot instance
- launched-by-autospotting 
- launched-for-asg

**Comment by cristim** [comment]
Thanks, this is a known issue and should be solved after we merge https://github.com/AutoSpotting/AutoSpotting/pull/354

Please give that a try and provide feedback, I'd love to have that merged but it needs more testing and increased test coverage. Any help on that is more than welcome.
