### ISSUE TITLE
Missing variable

### ISSUE THREAD

**Issue by grahamlyons** [LeanerCloud/terraform-aws-autospotting#3]
Trying to use the module from the master branch, as per the instructions, fails because of a missing variable declaration:
`Error: module 'aws_lambda_function': unknown variable referenced: 'autospotting_instance_termination_method'; define it with a 'variable' block`

The `variable` block for this variable - https://github.com/AutoSpotting/terraform-aws-autospotting/blob/620b584/main.tf#L29 - is missing.

**Comment by bfin** [comment]
Sorry, that was sloppy on my part. Will submit fix w/i the hour
