### ISSUE TITLE
'autospotting_regions_enabled' variable is not respected in v0.1.5 and v0.1.6

### ISSUE THREAD

**Issue by vikas027** [LeanerCloud/terraform-aws-autospotting#34]
I have below code which works absolutely fine i.e. the lambda gets deployed only ap-southeast-2 region but when I switch to the v0.1.5 or v0.1.6, the module tries to deploy the lambda in all available regions.

```hcl
module autospotting {
  source                                    = "github.com/autospotting/terraform-aws-autospotting?ref=0.1.4"
  autospotting_regions_enabled              = "ap-southeast-2*"
  autospotting_tag_filters                  = "spot_enabled=true"
  autospotting_allowed_instance_types       = "m4.large,m4.xlarge"
<redacted>
}
```

It looks like this issue has started after this commit [28f8be4](https://github.com/AutoSpotting/terraform-aws-autospotting/commit/28f8be40b574e0e9769669fbf4a41ff7f17acdf1) or perhaps I am missing a new configuration variable?

**Comment by cristim** [comment]
This is not very accurate, this value is respected by the AutoSPotting code, which should still only run in the same way as before, it's just not respected by the Terraform code which still creates regional infrastructure everywhere.

**Comment by vikas027** [comment]
Thanks, @cristim . I will close this ticket for now, also will try to raise a PR to use it in Terraform as well (as time permits).
