### ISSUE TITLE
Errors shown when setting up autospotting via Terraform

### ISSUE THREAD

**Issue by lightninglife** [LeanerCloud/terraform-aws-autospotting#38]
$ aws configure list
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                <not set>             None    None
access_key     ****************YFEA shared-credentials-file    
secret_key     ****************ySVh shared-credentials-file    
    region                us-east-1      config-file    ~/.aws/config

$ terraform plan

Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid.
	status code: 403, request id: a690e245-e650-49d5-9418-ea778ae83dd0

**Comment by cristim** [comment]
Looks like an issue with the recent multi-regional code, by default we create provider configuration for all available regions. It sometimes might return such errors in case some of the regions need to be enabled for your account.

Try to configure AutoSpotting to only run against a smaller set of regions, as you can see in the examples directory. You'll also need to delete the multi-regional providers.tf and have it re-generated with the smaller set of regions.

If you figure out which region causes this issue we can add it to the existing blacklist.

**Comment by lightninglife** [comment]
Hi Cristim,

Thanks for replying me. I'm wondering where I should I edit in order to limit regions targeted. I'm a bit of confused with tons of files. Under example directory, there is only one main.tf file.

**Comment by cristim** [comment]
Under `modules/regional` delete`regional.tf`, the example just show how to set it up to run with less regions, by default it's running against all available regions.

Once you set a short list of regions the file you deleted will be re-generated if you run Terraform apply once. Then run Terraform again to create the regional resources.

I've tried to make a default that covers all regions without requiring configuration changes, but unfortunately some regions don't work, in my tests a few weeks ago I noticed that for the Osaka region, but there might be other more recently launched regions that make it fail for you. I guess I'll reduce the list to a core set of regions and document the process to add more if needed.

**Comment by cristim** [comment]
@lightninglife have you figured it out?

**Comment by lightninglife** [comment]
Hi Cristian,

I’ll work on it today. Thanks for reaching out to me.

Paul

**Comment by lightninglife** [comment]
Hi Cristian, 

Under main.tf file, I found this part to be edit

locals {
  all_regions         = data.aws_regions.current.names
  unsupported_regions = ["ap-northeast-3"] # These regions currently throw an error when attempting to use them.

After editing with codes below

locals {
  all_regions         = data.aws_regions.current.names
  unsupported_regions = ["ap-northeast-3”, “af-south-1”, “ap-east-1”, “ap-northeast-1”, “ap-northeast-2”, “ap-south-1”, “ap-southeast-1”, “ap-southeast-2”, “me-south-1”, “sa-east-1”]

I got errors below

Quoted strings may not be split over multiple lines. To produce a multi-line
string, either use the \n escape to represent a newline character or use the
"heredoc" multi-line template syntax.

**Comment by cristim** [comment]
Thanks!
This errors means that you have a multi-line value, which seems to not be supported by terraform, just concatenate everything in a single line and it should work.

I'd like to eventually see a smaller list of unsupported regions, once you have it working please try to bisect the items until you get to the minimalist list of unsupported regions.

**Comment by lightninglife** [comment]
Hi Cristian, 

I just tried everything on my RHEL 8.3 using VirutalBox on Windows 10 laptop. It went through. I'll test it on RHEL 8.3 using VirtualBox on Mac.

Thank you so much for your help!

Best Regards,
Paul

**Comment by tonycosentini** [comment]
Hi,

Is there any workaround for this for anyone using a service like Terraform Cloud? The fix works fine for me locally, but on Terraform Cloud (when using the remote execution mode), there's no way to manually modify the module source.

**Comment by cristim** [comment]
I think the best way forward is to change the logic to pick a set of working regions commonly used and to require users to opt in for more.

I don't have time to work on this over the next few weeks but I would accept any pull requests addressing this properly.

**Comment by cristim** [comment]
Fixed in d55a5ab83cd4c3c4f05f81b3368fee32f96a4d3b, also available in the tag 0.2.1
