### ISSUE TITLE
After creating resources, only us-east-1 has lambda functions built up not in other regions

### ISSUE THREAD

**Issue by lightninglife** [LeanerCloud/terraform-aws-autospotting#39]
Hi there,

As terraform apply is completed, only below resources created in us-east-1 region. I tested autospotting, it did work. But how would I be able to enable autospotting service in other regions with lambda functions set up. Thanks!

![image](https://user-images.githubusercontent.com/23303708/103929917-f56c8a80-50eb-11eb-9853-1ce5873a48e3.png)

Paul

**Comment by cristim** [comment]
Hi Paul and thanks for reporting this.

The above Lambda functions implement the most of the AutoSpotting logic, and they only have to be deployed in a single region. When invoked in cron mode the main Lambda function will work against all the other regions, unless the list of regions is restricted by the configuration. For the main region us-east-1 is the default but you can get it deployed in another region using custom binaries stored in your own s3 bucket created in another region.

All the other regions should have an additional Lambda function and a few ancillary resources that capture regional Cloudwatch events and forward them to the main Lambda function, which is able to process them. This is what's powering the relatively recent event-based instance replacement logic and the graceful spot termination handling, since the main Lambda function can't get the events from the other regions, we must forward them. 

This regional infrastructure may be missing in case you delete the regional Terraform code and only executed Terraform once. The regional Terraform code should be regenerated when running terraform once but you have to run Terraform again in order to create the regional resources. If you don't have the regional resources AutoSpotting will only run in the legacy cron mode and won't handle the spot termination events.

The quirk of running Terraform twice is unfortunately the only way I found to achieve this sort of configuration with the current version of Terraform, but I'm open to suggestions and/or hope to be able to avoid it with a future version.

**Comment by lightninglife** [comment]
Hi Cristim,

Thanks a lot, will try other regions using custom binaries.

Paul

**Comment by cristim** [comment]
You don't need to, and it won't help you get more than what you have already.

Try to just run Terraform apply again for creating the regional resources using the terraform code generated by the first terraform apply run

**Comment by lightninglife** [comment]
Hi Cristim, 

When trying to run terraform apply, following errors occur, I need to limit regions to see which region caused the issue?

Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid.
        status code: 403, request id: dc67277d-8ffe-4aab-8a4c-6e3bb82d173f



Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid.
        status code: 403, request id: 2050c94f-51ad-4857-a5e3-03442aa23670



Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid.
        status code: 403, request id: a6b8e402-50b0-4f29-b4c5-243dd1dddb91



Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid.
        status code: 403, request id: ae0d77c4-7ef6-4694-8f3a-851ae3674d84

**Comment by lightninglife** [comment]
Hi Cristim,

I terraform apply second time after setting up regions as shown below

locals {
  all_regions         = data.aws_regions.current.names
  unsupported_regions = [
    "ap-northeast-3",
    "af-south-1",
    "ap-*",
    "ca-*",
    "me-south-1",
    "sa-east-1",
    "eu-*",
    "us-west-*"
] # These regions currently throw an error when attempting to use them. This is also set in modules/regional/generate_regional_code.tf


Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid.
        status code: 403, request id: e4c87284-1b03-4102-abb8-c9d02ff15780



Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid.
        status code: 403, request id: 86a3042e-ce3e-4d43-ab0e-18285ae40877

**Comment by lightninglife** [comment]
Hi Cristim,

Thank you, I successfully added lambda function in other regions by terraform init and terraform apply after updating unsupported regions. Much appreciated for guiding me through!

Paul

**Comment by cristim** [comment]
Glad to hear that you figured it out. Please share what you did so we can get it documented for other people

**Comment by lightninglife** [comment]
Hi Cristim,

Here's my approach, I excluded every other regions except for us-east-1 and us-east-2

The current version only supports us-east-1 region as default. To apply this autospotting lambda function to other regions, we need to do terraform init and terraform apply two times. I tested on my own. 
In my case, I excluded every other region but us-east-1 and us-east-2 .
vim main.tf
for unsupported_regions , input all regions you don't want your autospotting to be applied. 
Also, there are certain regions that may throw errors, you may exclude those regions as required
locals {
  all_regions         = data.aws_regions.current.names
  unsupported_regions = [
    "ap-northeast-3",
    "ap-east-1",
    "af-south-1",
    "aws.ap-east-1",
    "ap-northeast-1",
    "ap-northeast-2",
    "ap-south-1",
    "ap-southeast-1",
    "ap-southeast-2",
    "ca-central-1",
    "eu-central-1",
    "eu-north-1",
    "eu-south-1",
    "eu-west-1",
    "eu-west-2",
    "eu-west-3",
    "me-south-1",
    "sa-east-1",
    "us-west-1",
    "us-west-2"
] # These regions currently throw an error when attempting to use them. This is also set in modules/regional/generate_regional_code.tf

**Comment by cristim** [comment]
Thanks, that works but it isn't the expected way to use the `unsupported_regions` variable. This is just supposed to be used for special regions that require sign-up through your TAM, such as the Osaka-local region set there initially. The problem you ran into is that there may have been more such regions launched recently, we just had the re:invent and multiple new announced regions, and this list would need to be kept up-to-date after such new region launches. 

If you want to restrict to certain regions the proper way would be to just set the `autospotting_regions_enabled` variable to list your desired regions, us-east-1 and us-east-2.

You can also see this in the Terraform example at https://github.com/AutoSpotting/terraform-aws-autospotting/blob/master/examples/main.tf#L13

I guess it makes sense to set the autospotting_regions_enabled default value to a relatively wide but safe set of regions and leave it to people to extend it further.

**Comment by lightninglife** [comment]
Hi Cristim,

I tried this approach, it threw errors like before. I bet it's better off to exclude every single one and then see if the regions required may cause the issue or not.

Paul

**Comment by cristim** [comment]
Yeah, I've seen, but that's strange.

I'll try to come up with a fix so that it works out of the box for a large set of regions and also to better document this quirky deployment process for people who run it in other regions.

**Comment by lightninglife** [comment]
Hi Cristian,

Much appreciated!

Paul

**Comment by cristim** [comment]
The issues you mentioned were fixed recently in d55a5ab83cd4c3c4f05f81b3368fee32f96a4d3b and release 0.2.1, please let me know if you still notice any such issues by reopening this issue.
