### ISSUE TITLE
ON_DEMAND_MULTIPLIER tag not behaving as expected

### ISSUE THREAD

**Issue by ehardwick-r7** [LeanerCloud/terraform-aws-autospotting#41]
When leveraging the on_demand_multiplier tag we are seeing behavior where it is multiplied by the on demand price twice. 

Current workaround is to leverage the square root instead of the actual on_demand_multipler price that we wish to use.   

Example: 
In the logs we can see: 

- Comparing current type t3.medium with price 0.01867424 with candidate x2gd.8xlarge with price 0.9262. 
- Our on_demand_multiplier = .67
- Region = us-east-1 
- on demand multiplier is .67 - 0.0416 * 0.67 * 0.67 = 0.01867424 where 0.416 is the on-demand hourly cost of t3.medium in us-east-1

**Comment by cristim** [comment]
Thanks for reporting this, it should be fixed on https://github.com/cloudutil/AutoSpotting/commit/69380271f3ee4c7da97aff62a595fb8a0b126a0c

Let me know if you still notice any issues.
