### ISSUE TITLE
IAM permissions missing from Lambda role

### ISSUE THREAD

**Issue by jjones-smug** [LeanerCloud/terraform-aws-autospotting#42]
The CloudFormation version of the IAM role used for the Lambda includes some permissions that are not in the Terraform version.

Of those, I found it was necessary to add the following in order to get the Lambda working.

ec2:CreateLaunchTemplate
ec2:CreateFleet
ec2:DeleteLaunchTemplate

**Comment by cristim** [comment]
Should be fixed in the current version.

The Terraform code is now tagged to match the AutoSpotting version from the AWS marketplace it's supposed to be used with.

Using it with another version may cause incompatibilities like what you noticed.
