### ISSUE TITLE
AutoSpotting binary file wrong case

### ISSUE THREAD

**Issue by richardj-bsquare** [LeanerCloud/terraform-aws-autospotting#6]
The auto-spotting go binary produced by Autospotting in github and placed in the lambda.zip is named 'AutoSpotting'...

This terraform module invokes 'autospotting' which cannot be found. To verify you can look at the nightly builds at  https://cloudprowess.s3.amazonaws.com/nightly/lambda.zip

Expected:
```
START RequestId: bb2a1ad7-3c44-4353-87a7-c90b68e9bbe8 Version: $LATEST
14:12:54 2019/04/24 14:12:54 Starting autospotting agent, build nightly-6893e7b
14:12:54 2019/04/24 14:12:54 Parsed command line flags: regions='eu*' min_on_demand_number=1 min_on_demand_percentage=0.0 allowed_instance_types= disallowed_instance_types= on_demand_price_multiplier=1.00 spot_price_buffer_percentage=10.000 bidding_policy=normal tag_filters=autospot tag_filter_mode=opt-in spot_product_description=Linux/UNIX (Amazon VPC) instance_termination_method=autoscaling termination_n
14:12:54 2019/04/24 14:12:54 main.go:123: Scanning for available AWS regions
...
```
Actual:
```
14:10:37 START RequestId: 3d8a4014-5d5f-4502-b9a3-e3fe1df11259 Version: $LATEST
14:10:37 fork/exec /var/task/autospotting: no such file or directory: PathError null
14:10:37 END RequestId: 3d8a4014-5d5f-4502-b9a3-e3fe1df11259
```

The expected result was achieved by manually updating the handler in the lambda function to be 'AutoSpotting' ; the code change would be at:
https://github.com/AutoSpotting/terraform-aws-autospotting/blob/master/modules/lambda/main.tf#L15

**Comment by cristim** [comment]
Thanks, for reporting this, it's a known issue after the migration to Go modules.

Please create a pull request.

**Comment by richardj-bsquare** [comment]
Pull request #7

**Comment by cristim** [comment]
Thank you for the fix, much appreciated!

**Comment by richardj-bsquare** [comment]
Pull request #8 S3 location also has this issue.
