### ISSUE TITLE
Update for terraform 0.12

### ISSUE THREAD

**Issue by bfin** [LeanerCloud/terraform-aws-autospotting#9]
Terraform v0.12 is a major release with some breaking changes. This module currently only works with v0.11 or older.

https://www.terraform.io/upgrade-guides/0-12.html

**Comment by bfin** [comment]
@cristim Recommend tagging the last version as well as this version so users can more easily see that earlier versions are not compatible with terraform 0.12 and newer versions are not compatible with terraform 0.11. That would also put #2 to rest.

**Comment by cristim** [comment]
@bfin thanks for this contribution, the code looks so much cleaner without those curly braces!

I'll tag the code before and after I merge this.
